budgeteer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('budgeteer_app.urls', namespace="budgeteer")),
    path('admin/', admin.site.urls),
]

budgeteer_app/urls.py
from django.urls import path
from django.contrib import admin
# from django.views.generic import TemplateView
from . import views

app_name = 'budgeteer'

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('graph_view/', views.graph_view, name="graph_view"),
    path('category/delete/<pk>', views.delete_category, name="delete_category"),
    path('category/archive/<pk>', views.archive_category, name="archive_category"),
    path('transaction/<account_pk>/<transaction_pk>', views.delete_transaction, name="delete_transaction"),
    path('<username>/', views.profile, name="profile"),
    path('<username>/edit', views.edit, name="edit"),
    path('<username>/add_account', views.add_account, name="add_account"),
    path('<username>/categories', views.categories, name="categories"),
    path('<username>/budget/<year>/<month>', views.budget, name="budget"),
    path('<username>/<account_name>', views.account, name="account"),
    path('<username>/<account_name>/add_transaction', views.add_transaction, name="add_transaction"),
]

budgeteer_app/forms.py
# from django import forms
from django.forms import ModelForm, Select, DateField
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User, Account, Transaction, TransactionCategory
from django import forms
from budgeteer.settings import DATE_INPUT_FORMATS


# Form to log a user into their account
class CustomUserAuthForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User
        fields = ('username', 'password')

    def clean_username(self):
        return self.cleaned_data['username'].lower()


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'password1', 'password2']


class AddAccountForm(ModelForm):
    class Meta(ModelForm):
        model = Account
        fields = ['account_name', 'account_type', 'starting_balance']
        widgets = {
            'account_type': Select(attrs={'style': 'display: block;'}), }


class AddTransactionForm(ModelForm):
    date = forms.DateField(input_formats=DATE_INPUT_FORMATS,)
    class Meta:
        model = Transaction
        fields = ('date', 'amount', 'transaction_type', 'category', 'notes')
        widgets = {'transaction_type': Select(attrs={'style': 'display: block;'}),
                   'category': Select(attrs={'style': 'display: block;'}), }


class AddExpenseCategory(ModelForm):
    class Meta:
        model = TransactionCategory
        fields = ('category',)


class EditUser(forms.Form):
    username = forms.CharField(max_length=100)
    display_name = forms.CharField(max_length=100)

    # class Meta:
    #     model = User
    #     fields = ('username', 'display_name')

budgeteer_app/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserAuthForm, CustomUserCreationForm, AddAccountForm, AddTransactionForm, AddExpenseCategory
from django.contrib.auth import logout as lout
from django.contrib import messages
from .models import Transaction, TransactionCategory, TransactionType, Account, Budget
from django.forms import modelformset_factory
from .view_helpers.add_transaction import get_categories, validate_transaction_formset, clean_formset
from .view_helpers.general import accounting_num
from .view_helpers.delete_transaction import delete_offset
from .view_helpers.graphing import graph
from .view_helpers.categories import create_category
from .view_helpers.add_account import validate_account_form
from .view_helpers.register import validate_registration
from .view_helpers.login import validate_login
from .view_helpers.edit import update_user
from .view_helpers.budget import getDates
from django.db.models import Sum
import datetime


def home(request):
    if request.user.is_authenticated:
        return redirect("budgeteer:profile", request.user.username)
    else:
        return render(request, template_name="budgeteer/home.html")


def login(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are already logged in!")
        return redirect(f'/{request.user.username}')
    else:
        if request.method == "POST":
            form = CustomUserAuthForm(request, data=request.POST)
            return validate_login(request, form)

        form = CustomUserAuthForm
        return render(request, "budgeteer/login.html", {"form": form})


def logout(request):
    lout(request)
    return redirect('budgeteer:home')


def register(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are logged in, please log out if you want to register")
        return redirect(f'/{request.user.username}')
    else:
        if request.method == "POST":
            form = CustomUserCreationForm(request.POST)
            return validate_registration(request, form)

        form = CustomUserCreationForm()
        return render(request, 'budgeteer/register.html', {"form": form})


def profile(request, username):

    if username == "admin":
        return redirect('budgeteer:admin')

    if request.user.is_authenticated and request.user.username == username:
        net_worth = 0
        accounts = request.user.account_set.all()
        user_accounts = []

        for each_account in accounts:
            net_worth += each_account.current_balance
            user_accounts.append({"name": each_account.account_name,
                                  "balance": accounting_num(each_account.current_balance),
                                  "account": each_account})

        month = int(datetime.datetime.now().strftime("%m"))
        year = int(datetime.datetime.now().strftime("%Y"))

        return render(request, "budgeteer/profile/profile.html", {"accounts": user_accounts,
                                                                  "netWorth": accounting_num(net_worth),
                                                                  "month": month,
                                                                  "year": year})
    else:
        return redirect('budgeteer:home')


def add_account(request, username):
    if request.user.is_authenticated and request.user.username == username:
        if request.method == "POST":
            form = AddAccountForm(request.POST)
            return validate_account_form(request, form)

        form = AddAccountForm()
        return render(request, "budgeteer/profile/account/add_account.html", {"form": form})
    else:
        return redirect('budgeteer:home')


def add_transaction(request, username, account_name):
    if request.user.is_authenticated and request.user.username == username:
        transaction_formset = modelformset_factory(Transaction, form=AddTransactionForm)
        expense_categories, income_categories, transfer_categories, value_adjust_categories = get_categories(request)
        context = {"formset": transaction_formset, "expense_categories": expense_categories,
                   "income_categories": income_categories, "transfer_categories": transfer_categories,
                   "value_adjust_categories": value_adjust_categories}

        if request.method == 'POST':
            formset = transaction_formset(request.POST)
            cleaned_formset = clean_formset(request, formset)
            context['formset'] = cleaned_formset

            return validate_transaction_formset(request, cleaned_formset, account_name, context)

        else:
            data = {'form-TOTAL_FORMS': '10',
                    'form-INITIAL_FORMS': '0',
                    'form-MAX_NUM_FORMS': ''}

            formset = transaction_formset(data, queryset=Transaction.objects.filter(account__user=request.user))
            context['formset'] = formset

            for form in formset:
                form.fields['date'].widget.attrs['class'] = 'datepicker'

        return render(request, 'budgeteer/profile/add_transaction.html', context)

    else:
        return redirect('budgeteer:home')


def account(request, username, account_name):
    display_account = request.user.account_set.filter(account_name=account_name)[0]
    transactions = display_account.transaction_set.all()
    return render(request, 'budgeteer/profile/account/account.html', {"account": display_account,
                                                                      "transactions": transactions,
                                                                      "username": username})


def categories(request, username):
    if request.user.is_authenticated and request.user.username == username:

        user = request.user
        expense = TransactionType.objects.get(type_name="Expense")
        income = TransactionType.objects.get(type_name="Income")
        transfer = TransactionType.objects.get(type_name="Transfer")

        expense_categories = TransactionCategory.objects.filter(user=user, transaction_type=expense)
        income_categories = TransactionCategory.objects.filter(user=user, transaction_type=income)
        transfer_categories = TransactionCategory.objects.filter(user=user, transaction_type=transfer)

        expense_category_form = AddExpenseCategory(prefix="expense_category")
        income_category_form = AddExpenseCategory(prefix="income_category")

        context = {"expense_categories": expense_categories, "income_categories": income_categories,
                   "transfer_categories": transfer_categories, "expense_form": expense_category_form,
                   "income_form": income_category_form}

        if request.method == 'POST':
            return create_category(request, context)

        return render(request, 'budgeteer/profile/categories.html', context=context)
    else:
        return redirect('budgeteer:home')


def delete_category(request, pk):
    category = TransactionCategory.objects.get(pk=pk)
    category.delete()

    messages.success(request, "Category Deleted")
    return redirect(f'/{request.user.username}/categories')


def archive_category(request, pk):
    category = TransactionCategory.objects.get(pk=pk)

    if category.archived:
        category.archived = False
        messages.success(request, "Category Archived")
    else:
        category.archived = True
        messages.success(request, "Category Unarchived")

    category.save()

    return redirect(f'/{request.user.username}/categories')


def delete_transaction(request, account_pk, transaction_pk):
    transaction_account = Account.objects.get(pk=account_pk)
    transaction = Transaction.objects.get(pk=transaction_pk)
    balance_adjustment = transaction.amount

    if transaction.transaction_type.type_name == "Income" or transaction.category.category[:4] == "From":
        balance_adjustment = -transaction.amount

    transaction_account.current_balance += balance_adjustment
    transaction_account.save()

    if transaction.transaction_type.type_name == "Transfer":
        delete_offset(request, transaction)

    transaction.delete()

    messages.success(request, "Transaction Deleted")
    return redirect(f'/{request.user.username}/{transaction_account.account_name}')


def graph_view(request):
    return graph(request)


def edit(request, username):
    if request.user.is_authenticated and request.user.username == username:
        return update_user(request)
    else:
        return redirect('budgeteer:home')


def budget(request, username, month, year):
    budget_objects = Budget.objects.filter(transaction_category__user=request.user).order_by('transaction_category')
    actual_amounts = dict()
    for budget in budget_objects:
        sum = Transaction.objects.filter(account__user=request.user,
                                         category__category=budget.transaction_category.category,
                                         date__month=int(month), date__year=int(year)).aggregate(Sum('amount'))

        actual_amounts[budget.transaction_category.category] = round(sum['amount__sum'], 2) if sum['amount__sum'] else 0

        dates = getDates(month, year)

    context = {"budgets": budget_objects, "actuals": actual_amounts, "dates": dates}


    if request.user.is_authenticated and request.user.username == username:
        return render(request, 'budgeteer/profile/budget/budget.html', context=context)
    else:
        return redirect('budgeteer:home')

budgeteer_app/templates/budgeteer/includes/footer.html
{#<div class="container">#}
{#    <div class="row">#}
{#        <div class="col l6 s12">#}
{#            <h5 class="white-text">Footer Content</h5>#}
{#            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>#}
{#        </div>#}
{#        <div class="col l4 offset-l2 s12">#}
{#            <h5 class="white-text">Links</h5>#}
{#            <ul>#}
{#                <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>#}
{#                <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>#}
{#                <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>#}
{#                <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<div class="footer-copyright teal lighten-4">
    <div class="container teal-text text-lighten-1">
            © 2020 Cory Loughran
        <a class="grey-text text-lighten-4 right" href="#!"></a>
    </div>
</div>

budgeteer_app/templates/budgeteer/includes/messages.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success'%}
      <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
    {% elif message.tags == 'info'%}
      <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
    {% elif message.tags == 'warning'%}
       <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:4000});</script>
    {% elif message.tags == 'error'%}
       <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:4000});</script>
    {% endif %}
  {% endfor %}
{% endif %}

budgeteer_app/templates/budgeteer/includes/nav.html
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content teal lighten-5">
    <li><a href="/">Dashboard</a></li>
    <li><a href="{% url 'budgeteer:edit' request.user.username %}">Edit Profile</a></li>
    <li><a href="{% url 'budgeteer:categories' request.user.username %}">Edit Transaction Categories</a></li>
    <li><a href="{% url 'budgeteer:add_account' request.user.username %}">Add an Account</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'budgeteer:logout' %}">Logout</a></li>
</ul>


<nav class="teal lighten-4">
    <div class="nav-wrapper">
        <div class="container">
            {% if request.user.is_authenticated %}
                <a href="/{{ request.user.username }}" class="brand-logo teal-text text-lighten-1">Budgeteer</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger teal-text text-lighten-1"><i class="material-icons">menu</i></a>
            {% else %}
                <a href="{%  url 'budgeteer:home' %}" class="brand-logo teal-text text-lighten-1">Budgeteer</a>
            {% endif %}
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if request.user.is_authenticated %}
                    <li id="nav-dislay-name" class="teal-text text-lighten-1">
                        <a class="dropdown-trigger teal-text text-lighten-1" href="" data-target="dropdown1">
                            {{ request.user.display_name }}
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'budgeteer:login' %}" class="teal-text text-lighten-1">
                            Login
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'budgeteer:register' %}" class="teal-text text-lighten-1">
                            Register
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<ul class="sidenav teal lighten-4" id="mobile-demo">
    <li><a href="/" class="teal-text text-lighten-1">Dashboard</a></li>
    <li><a href="{% url 'budgeteer:edit' request.user.username %}" class="teal-text text-lighten-1">Edit Profile</a></li>
    <li><a href="{% url 'budgeteer:categories' request.user.username %}" class="teal-text text-lighten-1">Edit Transaction Categories</a></li>
    <li><a href="{% url 'budgeteer:add_account' request.user.username %}" class="teal-text text-lighten-1">Add an Account</a></li>
    <li class="divider"></li>
    <li><a href="{% url 'budgeteer:logout' %}" class="teal-text text-lighten-1">Logout</a></li>
</ul>

<script>
    $(document).ready(function() {
        $(".dropdown-trigger").dropdown({ hover: true });
    });

    $(document).ready(function(){
        $('.sidenav').sidenav();
    });

</script>