budgeteer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('budgeteer_app.urls', namespace="budgeteer")),
    path('admin/', admin.site.urls),
]

budgeteer_app/urls.py
from django.urls import path
from django.contrib import admin
# from django.views.generic import TemplateView
from . import views

app_name = 'budgeteer'

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', views.home, name="home"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
    path('graph_view/', views.graph_view, name="graph_view"),
    path('category/delete/<pk>', views.delete_category, name="delete_category"),
    path('category/archive/<pk>', views.archive_category, name="archive_category"),
    path('transaction/<account_pk>/<transaction_pk>', views.delete_transaction, name="delete_transaction"),
    path('<username>/', views.profile, name="profile"),
    path('<username>/edit', views.edit, name="edit"),
    path('<username>/add_account', views.add_account, name="add_account"),
    path('<username>/categories', views.categories, name="categories"),
    path('<username>/budget/<year>/<month>', views.budget, name="budget"),
    path('<username>/<account_name>', views.account, name="account"),
    path('<username>/<account_name>/add_transaction', views.add_transaction, name="add_transaction"),
]

budgeteer_app/forms.py
# from django import forms
from django.forms import ModelForm, Select, DateField
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User, Account, Transaction, TransactionCategory
from django import forms
from budgeteer.settings import DATE_INPUT_FORMATS


# Form to log a user into their account
class CustomUserAuthForm(AuthenticationForm):
    class Meta(AuthenticationForm):
        model = User
        fields = ('username', 'password')

    def clean_username(self):
        return self.cleaned_data['username'].lower()


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = User
        fields = ['username', 'password1', 'password2']


class AddAccountForm(ModelForm):
    class Meta(ModelForm):
        model = Account
        fields = ['account_name', 'account_type', 'starting_balance']
        widgets = {
            'account_type': Select(attrs={'style': 'display: block;'}), }


class AddTransactionForm(ModelForm):
    date = forms.DateField(input_formats=DATE_INPUT_FORMATS,)
    class Meta:
        model = Transaction
        fields = ('date', 'amount', 'transaction_type', 'category', 'notes')
        widgets = {'transaction_type': Select(attrs={'style': 'display: block;'}),
                   'category': Select(attrs={'style': 'display: block;'}), }


class AddExpenseCategory(ModelForm):
    class Meta:
        model = TransactionCategory
        fields = ('category',)


class EditUser(forms.Form):
    username = forms.CharField(max_length=100)
    display_name = forms.CharField(max_length=100)

    # class Meta:
    #     model = User
    #     fields = ('username', 'display_name')

budgeteer_app/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserAuthForm, CustomUserCreationForm, AddAccountForm, AddTransactionForm, AddExpenseCategory
from django.contrib.auth import logout as lout
from django.contrib import messages
from .models import Transaction, TransactionCategory, TransactionType, Account, Budget
from django.forms import modelformset_factory
from .view_helpers.add_transaction import get_categories, validate_transaction_formset, clean_formset
from .view_helpers.general import accounting_num
from .view_helpers.delete_transaction import delete_offset
from .view_helpers.graphing import graph
from .view_helpers.categories import create_category
from .view_helpers.add_account import validate_account_form
from .view_helpers.register import validate_registration
from .view_helpers.login import validate_login
from .view_helpers.edit import update_user
from .view_helpers.budget import getDates
from django.db.models import Sum
import datetime


def home(request):
    if request.user.is_authenticated:
        return redirect("budgeteer:profile", request.user.username)
    else:
        return render(request, template_name="budgeteer/home.html")


def login(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are already logged in!")
        return redirect(f'/{request.user.username}')
    else:
        if request.method == "POST":
            form = CustomUserAuthForm(request, data=request.POST)
            return validate_login(request, form)

        form = CustomUserAuthForm
        return render(request, "budgeteer/login.html", {"form": form})


def logout(request):
    lout(request)
    return redirect('budgeteer:home')


def register(request):
    if request.user.is_authenticated:
        messages.warning(request, f"You are logged in, please log out if you want to register")
        return redirect(f'/{request.user.username}')
    else:
        if request.method == "POST":
            form = CustomUserCreationForm(request.POST)
            return validate_registration(request, form)

        form = CustomUserCreationForm()
        return render(request, 'budgeteer/register.html', {"form": form})


def profile(request, username):

    if username == "admin":
        return redirect('budgeteer:admin')

    if request.user.is_authenticated and request.user.username == username:
        net_worth = 0
        accounts = request.user.account_set.all()
        user_accounts = []

        for each_account in accounts:
            net_worth += each_account.current_balance
            user_accounts.append({"name": each_account.account_name,
                                  "balance": accounting_num(each_account.current_balance),
                                  "account": each_account})

        month = int(datetime.datetime.now().strftime("%m"))
        year = int(datetime.datetime.now().strftime("%Y"))

        return render(request, "budgeteer/profile/profile.html", {"accounts": user_accounts,
                                                                  "netWorth": accounting_num(net_worth),
                                                                  "month": month,
                                                                  "year": year})
    else:
        return redirect('budgeteer:home')


def add_account(request, username):
    if request.user.is_authenticated and request.user.username == username:
        if request.method == "POST":
            form = AddAccountForm(request.POST)
            return validate_account_form(request, form)

        form = AddAccountForm()
        return render(request, "budgeteer/profile/account/add_account.html", {"form": form})
    else:
        return redirect('budgeteer:home')


def add_transaction(request, username, account_name):
    if request.user.is_authenticated and request.user.username == username:
        transaction_formset = modelformset_factory(Transaction, form=AddTransactionForm)
        expense_categories, income_categories, transfer_categories, value_adjust_categories = get_categories(request)
        context = {"formset": transaction_formset, "expense_categories": expense_categories,
                   "income_categories": income_categories, "transfer_categories": transfer_categories,
                   "value_adjust_categories": value_adjust_categories}

        if request.method == 'POST':
            formset = transaction_formset(request.POST)
            cleaned_formset = clean_formset(request, formset)
            context['formset'] = cleaned_formset

            return validate_transaction_formset(request, cleaned_formset, account_name, context)

        else:
            data = {'form-TOTAL_FORMS': '10',
                    'form-INITIAL_FORMS': '0',
                    'form-MAX_NUM_FORMS': ''}

            formset = transaction_formset(data, queryset=Transaction.objects.filter(account__user=request.user))
            context['formset'] = formset

            for form in formset:
                form.fields['date'].widget.attrs['class'] = 'datepicker'

        return render(request, 'budgeteer/profile/add_transaction.html', context)

    else:
        return redirect('budgeteer:home')


def account(request, username, account_name):
    display_account = request.user.account_set.filter(account_name=account_name)[0]
    transactions = display_account.transaction_set.all()
    return render(request, 'budgeteer/profile/account/account.html', {"account": display_account,
                                                                      "transactions": transactions,
                                                                      "username": username})


def categories(request, username):
    if request.user.is_authenticated and request.user.username == username:

        user = request.user
        expense = TransactionType.objects.get(type_name="Expense")
        income = TransactionType.objects.get(type_name="Income")
        transfer = TransactionType.objects.get(type_name="Transfer")

        expense_categories = TransactionCategory.objects.filter(user=user, transaction_type=expense)
        income_categories = TransactionCategory.objects.filter(user=user, transaction_type=income)
        transfer_categories = TransactionCategory.objects.filter(user=user, transaction_type=transfer)

        expense_category_form = AddExpenseCategory(prefix="expense_category")
        income_category_form = AddExpenseCategory(prefix="income_category")

        context = {"expense_categories": expense_categories, "income_categories": income_categories,
                   "transfer_categories": transfer_categories, "expense_form": expense_category_form,
                   "income_form": income_category_form}

        if request.method == 'POST':
            return create_category(request, context)

        return render(request, 'budgeteer/profile/categories.html', context=context)
    else:
        return redirect('budgeteer:home')


def delete_category(request, pk):
    category = TransactionCategory.objects.get(pk=pk)
    category.delete()

    messages.success(request, "Category Deleted")
    return redirect(f'/{request.user.username}/categories')


def archive_category(request, pk):
    category = TransactionCategory.objects.get(pk=pk)

    if category.archived:
        category.archived = False
        messages.success(request, "Category Archived")
    else:
        category.archived = True
        messages.success(request, "Category Unarchived")

    category.save()

    return redirect(f'/{request.user.username}/categories')


def delete_transaction(request, account_pk, transaction_pk):
    transaction_account = Account.objects.get(pk=account_pk)
    transaction = Transaction.objects.get(pk=transaction_pk)
    balance_adjustment = transaction.amount

    if transaction.transaction_type.type_name == "Income" or transaction.category.category[:4] == "From":
        balance_adjustment = -transaction.amount

    transaction_account.current_balance += balance_adjustment
    transaction_account.save()

    if transaction.transaction_type.type_name == "Transfer":
        delete_offset(request, transaction)

    transaction.delete()

    messages.success(request, "Transaction Deleted")
    return redirect(f'/{request.user.username}/{transaction_account.account_name}')


def graph_view(request):
    return graph(request)


def edit(request, username):
    if request.user.is_authenticated and request.user.username == username:
        return update_user(request)
    else:
        return redirect('budgeteer:home')


def budget(request, username, month, year):
    budget_objects = Budget.objects.filter(transaction_category__user=request.user).order_by('transaction_category')
    actual_amounts = dict()
    for budget in budget_objects:
        sum = Transaction.objects.filter(account__user=request.user,
                                         category__category=budget.transaction_category.category,
                                         date__month=int(month), date__year=int(year)).aggregate(Sum('amount'))

        actual_amounts[budget.transaction_category.category] = round(sum['amount__sum'], 2) if sum['amount__sum'] else 0

        dates = getDates(month, year)

    context = {"budgets": budget_objects, "actuals": actual_amounts, "dates": dates}


    if request.user.is_authenticated and request.user.username == username:
        return render(request, 'budgeteer/profile/budget/budget.html', context=context)
    else:
        return redirect('budgeteer:home')

budgeteer_app/templates/budgeteer/profile/add_transaction.html
{% extends 'budgeteer/app.html' %}

{% block content %}



    <form method="POST">
        {{ formset.management_form }}
        <style>
            input[type="text"] {
                font-size: 95% !important;
            }

            input[type="number"] {
                font-size: 95% !important;
            }
        </style>
        <table id="add-transaction">
            <tr>
                <th>Date</th>
                <th>Amount</th>
                <th>Transaction Type</th>
                <th>Category</th>
                <th>Notes</th>
            </tr>

            {% for form in formset %}
                {% csrf_token %}
                <script>
                    $(document).ready(function() {
                        $('.datepicker').datepicker();
                    });
                </script>
                <tr>
{#                    <td hidden="True">{{ form.account }}</td>#}
                    <td width="10%">{{ form.date }}</td>
                    <td width="10%">{{ form.amount }}</td>
                    <td width="15%" onchange="type_update.call(this)">{{ form.transaction_type }}</td>
                    <td width="15%" onchange="selected.call(this)">{{ form.category }}</td>
                    <td width="35%">{{ form.notes }}</td>
                </tr>
            {% endfor %}
        </table>
        <button class="btn waves-effect teal lighten-2" type="submit">Add Transactions</button>

    </form>

    <script>

        function selected() {
            var selected = $(this).children().valueOf();
            console.log(selected);
        }

        function category_update(type, categories) {
            if (type === "Expense") {
                categories.append('<option>---------</option>');
                {% for category in expense_categories %}
                    categories.append('<option value="{{ category.pk }}">{{ category.category }}</option>');
                {% endfor %}
            } else if (type === "Income") {
                categories.append('<option>---------</option>');
                {% for category in income_categories %}
                    categories.append('<option value="{{ category.pk }}">{{ category.category }}</option>');
                {% endfor %}
            } else if (type === "Transfer") {
                categories.append('<option>---------</option>');
                {% for category in transfer_categories %}
                    categories.append('<option value="{{ category.pk }}">{{ category.category }}</option>');
                {% endfor %}
            } else {
                categories.append('<option>---------</option>');
            }
        }

        function categories() {
            for(i = 0; i < 10; i++) {

                var id = "#id_form-" + i + "-transaction_type";
                var other = "#id_form-" + i + "-category";

                var type = $(`${id} option:checked`)[0].text;

                var categories = $(`${other}`);
                categories.empty();

                category_update(type, categories);
            }
        }

        function type_update() {

            var type = this.children[0];
            type = type.options[type.selectedIndex].text;

            var categories = $(this).next().children();
            categories.empty();

            category_update(type, categories);
        }

        $(document).ready(function() {
            var select = $("select");

            for(i = 1; i < select.length; i = i + 2) {
                console.log($(select[i]));
                $(select[i]).empty();
            }
        });

    </script>

{% endblock %}

budgeteer_app/templates/budgeteer/profile/categories.html
{% extends 'budgeteer/app.html' %}

{% block content %}

    <div class="row">
        <div class="col s12">
            <h5>Edit Budget Categories</h5>
        </div>

        <div class="col s12 m6">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    <span class="card-title"><strong>Expense Categories</strong></span>
                    <div class="row">
                        {% for category in expense_categories %}
                            <p class="col m5 s4 category">{{ category.category }}</p>

                            <a href="/category/archive/{{ category.pk }}" class="col m3 s4">
                                <button class="btn waves-effect teal lighten-2 category-btn">
                                    {% if category.archived %}
                                        Unarchive
                                    {% else %}
                                        Archive
                                    {% endif %}
                                </button>
                            </a>

                            <a href="/category/delete/{{ category.pk }}" class="col m3 s4 offset-m1">
                                <button class="btn waves-effect teal lighten-2 category-btn" >Delete</button>
                            </a>

                        {% endfor %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ expense_form }}
                            <button class="btn waves-effect teal lighten-2" name="expense_category">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="col s12 m6">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    <span class="card-title"><strong>Income Categories</strong></span>
                    <div class="row">
                        {% for category in income_categories %}
                            <p class="col m5 s4 category">{{ category.category }}</p>

                            <a href="/category/archive/{{ category.pk }}" class="col m3 s4">
                                <button class="btn waves-effect teal lighten-2 category-btn">
                                    {% if category.archived %}
                                        Unarchive
                                    {% else %}
                                        Archive
                                    {% endif %}
                                </button>
                            </a>

                            <a href="/category/delete/{{ category.pk }}" class="col m3 s4 offset-m1">
                                <button class="btn waves-effect teal lighten-2 category-btn">Delete</button>
                            </a>

                        {% endfor %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ income_form }}
                            <button class="btn waves-effect teal lighten-2"
                                    name="income_category">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{#        <div class="col s12 m4">#}
{#            <div class="card teal lighten-4 teal-text text-lighten-1">#}
{#                <div class="card-content">#}
{#                    <span class="card-title"><strong>Transfer Categories</strong></span>#}
{#                    <P>Transfer categories are not editable, they are generated based on the accounts you have</P>#}
{#                    <br>#}
{#                    <div class="row">#}
{#                        {% for category in transfer_categories %}#}
{#                            <p class="col s8" style="margin: 15px 0px 15px 0px;">{{ category.category }}</p>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
    </div>



{% endblock %}

budgeteer_app/templates/budgeteer/profile/edit.html
{% extends 'budgeteer/app.html' %}

{% block content %}
    <div class="row">
        <div class="col s12 m4 offset-m4">
            <div class="card teal lighten-4 text-teal text-lighten-1">
                <div class="card-content">
                    <span class="card-title"><strong>Edit User Details</strong></span>
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            {{ field.label }}{{ field }}
                        {% endfor %}
                        <button class="btn waves-effect teal lighten-2" type="submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

budgeteer_app/templates/budgeteer/profile/profile.html
{% extends 'budgeteer/app.html' %}

{% block content %}

    <h1 class="center-align">My Dashboard</h1>

    <div class="row">

        <!-- Net Worth -->
        <div class="col s12 m4">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    <span class="card-title"><strong>Net Worth</strong></span>
                    <h3 class="center-align">${{ netWorth }}</h3>
                </div>
            </div>
        </div>

        <!-- Accounts Card -->
        <div class="col s12 m4">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    <span class="card-title"><strong>Accounts</strong></span>
                    <div class="row">
                        {% for account in accounts %}
{#                            <p class="col s8">{{ account.name }}: </p>#}
                            <a href="/{{ request.user.username }}/{{ account.name }}" class="col s8 teal-text text-darken-1">
                                {{ account.name }}
                            </a>

                            {% if account.balance|make_list|first == "-" %}
                                <p class="col s4 red-text">${{ account.balance }}</p>
                            {% else %}
                                <p class="col s4">${{ account.balance }}</p>
                            {% endif %}
                        {% empty %}
                            <p class="col s12">No Accounts</p>
                        {% endfor %}
                    </div>
                    <a href="/{{ request.user.username }}/add_account" class="teal-text text-darken-1">Add an Account</a>
                </div>
            </div>
        </div>

        <!-- Transaction Categories -->
        <div class="col s12 m4">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    <span class="card-title">
                        <a href="/{{ request.user.username }}/budget/{{ year }}/{{ month }}" class="teal-text text-darken-1">
                            <strong>Edit Budget</strong>
                        </a>
                    </span>
                </div>
            </div>
        </div>

        <div class="col s12">
            <div class="card teal lighten-4 teal-text text-lighten-1">
                <div class="card-content">
                    {% if accounts %}
                        <img src="{% url 'budgeteer:graph_view' %}" alt="graph" style="width: 100%;" />
                    {% else %}
                        <p>No data to display: <a href="/{{ request.user.username }}/add_account"
                                                   class="teal-text text-darken-1">Add an Account</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}